name: chiche
version: 1.0
summary: An over-the-network, multi-player implimentation of Chinese Checkers in 3D.
description: Play a friendly game of Chinese Checkers against the computer or someone
  else on the network (provided you know their IP address), or some combination of the two.
  The playing board animates and is rendered in 3D using OpenGL.
confinement: devmode

apps:
  chiche:
    command: env SDL_AUDIODRIVER=pulseaudio desktop-launch $SNAP/bin/ChineseCheckers
    plugs: [home, x11, unity7, network, network-bind, pulseaudio, process-control]

parts:
  chiche:
    plugin: scons
    source: https://github.com/spencerparkin/ChineseCheckers.git
    source-branch: stable-release
    after: [desktop-gtk2]
